// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqR01HTuutoH8_jp-NmOp2of9_xNpnk8A',
    appId: '1:170865119745:web:b61f0493a0f73a44922600',
    messagingSenderId: '170865119745',
    projectId: 'workoutapp-b11bc',
    authDomain: 'workoutapp-b11bc.firebaseapp.com',
    storageBucket: 'workoutapp-b11bc.appspot.com',
    measurementId: 'G-DTBXW8NP71',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhz1M104BT_Br01P8wKeFBb6pgSyLnaTo',
    appId: '1:170865119745:android:2ef3096f2f8cef4f922600',
    messagingSenderId: '170865119745',
    projectId: 'workoutapp-b11bc',
    storageBucket: 'workoutapp-b11bc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-A0UAAt2KRPKfuTSPskFE5PwUZyAfO5Q',
    appId: '1:170865119745:ios:7d65a17590441078922600',
    messagingSenderId: '170865119745',
    projectId: 'workoutapp-b11bc',
    storageBucket: 'workoutapp-b11bc.appspot.com',
    iosClientId: '170865119745-emeakeh6jkm7mkhrdosugtag4coasr4h.apps.googleusercontent.com',
    iosBundleId: 'com.example.workoutApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-A0UAAt2KRPKfuTSPskFE5PwUZyAfO5Q',
    appId: '1:170865119745:ios:7d65a17590441078922600',
    messagingSenderId: '170865119745',
    projectId: 'workoutapp-b11bc',
    storageBucket: 'workoutapp-b11bc.appspot.com',
    iosClientId: '170865119745-emeakeh6jkm7mkhrdosugtag4coasr4h.apps.googleusercontent.com',
    iosBundleId: 'com.example.workoutApp',
  );
}


